#
# Build configuration for Circle CI
#
version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
general:
    artifacts:
        - /home/ubuntu/shopping-list-app/app/build/outputs/apk/

machine:
    environment:
        ANDROID_HOME: /usr/local/android-sdk-linux

dependencies:
    override:
        - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-28.0.0,android-28,extra-google-m2repository,extra-google-google_play_services,extra-android-support
        - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies

test:
    override:
        - (./gradlew assemble):
            timeout: 360